version: "3"
# see: https://taskfile.dev/usage/

tasks:
  build:
    cmds:
      - go build ./cmd/json-schema-validator
  release-build:
    cmds:
      - goreleaser --snapshot --clean
  fmt:
    shopt:
      - globstar
    cmds:
      - goimports -w ./**/*.go
  check:
    cmds:
      - golangci-lint run
