name: Workflows for pull-request

on:
  pull_request:
    branches:
      - main

jobs:
  path-filter:
    timeout-minutes: 30
    outputs:
      aqua: ${{steps.changes.outputs.aqua}}
      go: ${{steps.changes.outputs.go}}
      actions: ${{steps.changes.outputs.actions}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            aqua:
              - .github/workflows/_check-build.yml
              - .github/workflows/pull-request.yml
              - aqua.yaml
            go:
              - .github/workflows/pull-request.yml
              - .github/workflows/_lint.yml
              - ./**/*.go
              - go.mod
              - go.sum
            actions:
              - .github/workflows/*.yaml
              - .github/workflows/*.yml
  check-actions:
    needs: path-filter
    if: needs.path-filter.outputs.actions == 'true'
    uses: ./.github/workflows/_check-actions.yml
    permissions:
      contents: read
  check-golang:
    needs: path-filter
    if: needs.path-filter.outputs.go == 'true'
    uses: ./.github/workflows/_lint.yml
    permissions:
      contents: read
  check-build:
    needs: path-filter
    if: needs.path-filter.outputs.aqua == 'true'
    uses: ./.github/workflows/_check-build.yml
    permissions:
      contents: read
  status-check:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs:
      - check-actions
      - check-golang
      - check-build
    permissions: {}
    if: failure()
    steps:
      - run: exit 1
