name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        id: app-token
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: go
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 0
      - name: Set up Go
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      - name: Setup tools
        if: ${{ steps.release.outputs.release_created }}
        uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
        with:
          aqua_version: v2.40.0
      - name: Build
        run: task release-build
        if: ${{ steps.release.outputs.release_created }}
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jq ".[] | select(.type == \"Archive\") | .path" ./dist/artifacts.json | xargs gh release upload ${{ steps.release.outputs.tag_name }}
          jq -r ".[] | select(.type == \"Checksum\") | .path" ./dist/artifacts.json | xargs -I "{}" cp {} ./dist/checksums.txt
          gh release upload ${{ steps.release.outputs.tag_name }} ./dist/checksums.txt

