name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4.1.1
        id: release
        with:
          release-type: go
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 0
      - name: Set up Go
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      - name: Setup tools
        if: ${{ steps.release.outputs.release_created }}
        uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.28.0
      - name: Build
        run: task release-build
        if: ${{ steps.release.outputs.release_created }}
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jq ".[] | select(.type == \"Archive\") | .path" ./dist/artifacts.json | xargs gh release upload ${{ steps.release.outputs.tag_name }}
          jq -r ".[] | select(.type == \"Checksum\") | .path" ./dist/artifacts.json | xargs -I "{}" cp {} ./dist/checksums.txt
          gh release upload ${{ steps.release.outputs.tag_name }} ./dist/checksums.txt

