name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: go
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 0
      - name: Set up Go
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-go@v5
      - name: Setup tools
        if: ${{ steps.release.outputs.release_created }}
        uses: aquaproj/aqua-installer@v3.0.0
        with:
          aqua_version: v2.27.1
      - name: Build
        run: task release-build
        if: ${{ steps.release.outputs.release_created }}
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat ./dist/artifacts.json | jq ".[] | select(.type == \"Archive\") | .path" | xargs gh release upload ${{ steps.release.outputs.tag_name }}
          cat ./dist/artifacts.json | jq -r ".[] | select(.type == \"Checksum\") | .path" | xargs -I "{}" cp {} ./dist/checksums.txt
          gh release upload ${{ steps.release.outputs.tag_name }} ./dist/checksums.txt

