name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@a37ac6e4f6449ce8b3f7607e4d97d0146028dc0b # v4.1.0
        id: release
        with:
          release-type: go
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 0
      - name: Set up Go
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      - name: Setup tools
        if: ${{ steps.release.outputs.release_created }}
        uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
        with:
          aqua_version: v2.27.2
      - name: Build
        run: task release-build
        if: ${{ steps.release.outputs.release_created }}
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jq ".[] | select(.type == \"Archive\") | .path" ./dist/artifacts.json | xargs gh release upload ${{ steps.release.outputs.tag_name }}
          jq -r ".[] | select(.type == \"Checksum\") | .path" ./dist/artifacts.json | xargs -I "{}" cp {} ./dist/checksums.txt
          gh release upload ${{ steps.release.outputs.tag_name }} ./dist/checksums.txt

